[workspace]
members = ["crates/*"]

[workspace.package]
version = "1.0.0"
edition = "2024"
rust-version = "1.89" # keep sync with rust-toolchain.toml
license = "Apache-2.0"

[workspace.dependencies]
pyo3 = { version = "0.29.0", features = ["abi3-py310"] }
rayon = "1.12"
rand = "0.10"
dashmap = "6.1"