[build-system]
requires = ["pytest", "cython", "setuptools", "setuptools-rust", "wheel"]
build-backend = "setuptools.build_meta"

# If you find some configurations are similar to what qiskit does,
# yes, it does. I 'learned' from them.

[project]
name = "qurry"
dynamic = ["version", "readme", "dependencies"]
description = "Qurrium 📏 - The Measuring Tool for Renyi Entropy, Loschmidt Echo, and Magnetization Squared, The Library of Some Common Cases"
authors = [{ name = "Huai-Chung Chang", email = "harui2019@proton.me" }]
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">=3.10"

[project.urls]
Issues = "https://github.com/qurrium/qurrium/issues"
Homepage = "https://github.com/qurrium/qurrium"
Documentation = "https://docs.qurrium.org"

[tool.setuptools.packages.find]
include = ['qurry']
exclude = ['cmake', 'symengine', 'tests']

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = { file = "qurry/VERSION.txt" }
readme = { file = "README.md", content-type = "text/markdown" }
dependencies = { file = "requirements.txt" }

# cibuildwheel configuration for qurry
[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
skip = [
    "*-musllinux_i686", # rust tier 2 support, qiskit did not support musllinux
    "pp*",              # Qiskit and Qurrium are not pure python packages, See https://github.com/qurrium/qurry/issues/93#issuecomment-1801837481
    "cp38-*",           # Not support and won't support for we write type hint in 3.9 syntax.
    "*-musllinux_*",    # qiskit did not support musllinux
    # "*-manylinux_i686", # scipy dependency issue, Check issue https://github.com/qurrium/qurry/issues/93 for details
]
test-skip = "*win32 *linux_i686"
environment = { PATH = "$HOME/.cargo/bin:$PATH", RUSTUP_TOOLCHAIN = "stable" }
before-build = [
    'echo "======================================================================"',
    'echo "### Building ........................................................."',
    'echo "======================================================================"',
    'echo "| Which Python: "',
    'python -c "import sys; print(sys.executable)"',
    'python -c "from sysconfig import get_platform; print(get_platform())" || echo "| Failed to get platform..."',
    'echo "| Python Version: "',
    'python --version',
    'echo "| Platform: "',
    'python -c "import platform; print(platform.platform())"',
    'echo "| Install dependencies..."',
    "pip install --upgrade pipenv wheel pip",
    "pip install --upgrade auditwheel auditwheel-symbols delocate",
    "pip install --upgrade setuptools_rust setuptools wheel pkginfo",
]
before-test = [
    "echo ''",
    'echo "======================================================================"',
    'echo "### Testing Environment Preparing ...................................."',
    'echo "======================================================================"',
    "pip install --prefer-binary --only-binary=numpy,scipy numpy scipy",
    "pip install pytest pytest-xdist pytest-order",
    "pip install qiskit-aer",                                                        # For testing, qiskit-aer is required
    "pip install -r requirements-dev.txt --upgrade",
    "cd {project} && pip install . --upgrade && cd ..",
    'echo "======================================================================"',
    'echo "### Test Start ......................................................."',
    'echo "======================================================================"',
    "echo ''",
]
test-command = [
    "export JAX_ENABLE_X64=True",
    "pytest -n auto {project}/tests || pytest {project}/tests",
]

[tool.cibuildwheel.linux]
before-all = [
    "echo ''",
    'echo "| Clear .so files"',
    "find . -name '*.so' -delete",
    "find . -wholename '*/build' | xargs rm -rf",
    "find . -name 'dist' && rm -rf dist",
    "find . -name 'qurry.egg-info' && rm -rf qurry.egg-info",
    "find . -wholename '*/__pycache__' | xargs rm -rf",
    "find . -name 'target' && rm -rf target",
    "echo ''",
    'echo "======================================================================"',
    'echo "### Linux Setup ......................................................"',
    'echo "======================================================================"',
    'echo "| Installing Rust..."',
    "yum -y install libatomic",
    "command -v rustc >/dev/null 2>&1 || curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y",
    'command -v rustc >/dev/null 2>&1 || source "$HOME/.cargo/env"',
    "rustup show",
    'echo "| Rust ready"',
]

[tool.cibuildwheel.macos]
environment = "MACOSX_DEPLOYMENT_TARGET=10.12"
before-all = [
    "echo ''",
    'echo "| Clear .so files"',
    "find . -name '*.so' -delete",
    "find . -wholename '*/build' | xargs rm -rf",
    "find . -name 'dist' && rm -rf dist",
    "find . -name 'qurry.egg-info' && rm -rf qurry.egg-info",
    "find . -wholename '*/__pycache__' | xargs rm -rf",
    "find . -name 'target' && rm -rf target",
    "echo ''",
    'echo "======================================================================"',
    'echo "### MacOS Setup ......................................................"',
    'echo "======================================================================"',
    'echo "| Installing Rust..."',
    "command -v rustc >/dev/null 2>&1 || curl https://sh.rustup.rs -sSf | bash -s -- --default-toolchain=nightly --profile=minimal -y",
    'command -v rustc >/dev/null 2>&1 || source "$HOME/.cargo/env"',
    "rustup show",
    'echo "| Rust ready"',
    # "rustup target add x86_64-apple-darwin",
    # "rustup target add aarch64-apple-darwin",
    "pip install delocate pipx",
]
repair-wheel-command = "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel} && pipx run abi3audit --strict --report {wheel}"
# Attention: If you are building universal2 binaries, 
# confirm that you are using universal2 Python since version 3.10
# It can be check by `python -c "from setuptools._distutils.util import get_platform; print(get_platform())"`
# You should see something like `macosx-*-universal2` in the output.

[tool.cibuildwheel.windows]
# PowerShell script
# before-all = [
#     'Write-Host "Downloading..."',
#     "Invoke-WebRequest -Uri https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe -OutFile rustup-init.exe",
#     'Write-Host "Installing Rust..." -ForegroundColor Cyan',
#     'Start-Process -FilePath .\rustup-init.exe -ArgumentList "--default-toolchain nightly --profile minimal -y" -NoNewWindow -Wait',
#     'Remove-Item .\rustup-init.exe',
#     '$env:Path = "$env:USERPROFILE\.cargo\bin"',
#     "rustup show",
# ]

# CMD script
before-all = [
    "echo.",
    'echo "| Clear .so files"',
    'for /r %i in (*.so) do del %i',
    'rmdir /s /q build',
    'rmdir /s /q dist',
    'rmdir /s /q qurry.egg-info',
    'rmdir /s /q qurry\__pycache__',
    'rmdir /s /q qurry\capsule\__pycache__',
    'rmdir /s /q target',
    "echo ''",
    'echo "======================================================================"',
    'echo "### Windows Setup ...................................................."',
    'echo "======================================================================"',
    'echo "| Downloading Rust..."',
    "curl -o rustup-init.exe https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe",
    'echo "| Installing Rust..."',
    "rustup-init.exe --default-toolchain nightly --profile minimal -y",
    "del rustup-init.exe",
    'set PATH=%USERPROFILE%\.cargo\bin;%PATH%',
    "rustup show",
    'echo "| Rust ready"',
]
before-build = [
    'echo "======================================================================"',
    'echo "### Building ........................................................."',
    'echo "======================================================================"',
    'echo "| Install dependencies..."',
    "python -m pip install --upgrade pipenv wheel pip",
    "python -m pip install --upgrade auditwheel auditwheel-symbols delocate",
    "python -m pip install --upgrade setuptools_rust setuptools wheel pkginfo",
]
test-command = ["pytest {project}/tests"]

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
# Qiskit DeprecationWarning is very annoying,
# it can raise 100k+ warnings in a single test. WTF?

log_cli = false
testpaths = ["tests"]

[tool.coverage.run]
include = ["./qurry/*"]
omit = ["./tests/*"]
data_file = "./.coverage/.coverage"

# Linter and Formatter Configuration
# Pylint and Ruff are used for linting and formatting.
# We keep Pylint for it still supports more rules than Ruff.
[tool.pylint.format]
max-line-length = 100

[tool.pylint.design]
max-parents = 10

[tool.pylint.similarities]
ignore-docstrings = true
ignore-comments = true
min-similarity-lines = 6

[tool.pylint."messages control"]
disable = [
    "duplicate-code",                # R0801, Required further research
    "too-many-instance-attributes",  # R0902
    "too-few-public-methods",        # R0903
    "too-many-public-methods",       # R0904
    "too-many-branches",             # R0912
    "too-many-arguments",            # R0913
    "too-many-locals",               # R0914
    "too-many-statements",           # R0915
    "too-many-positional-arguments", # R0917
    "too-many-nested-blocks",        # R1702
]
# Respecting command line options of pylint
# This will be useful when you configure pylint in your IDE
# pylint ./qurry
# --max-line-length=100 --max-parents=10
# --ignore-docstrings --ignore-comments --min-similarity-lines=6
# --disable=R0801,R0902,R0903,R0904,R0912,R0913,R0914,R0915,R0917,R1702


[tool.ruff]
line-length = 100
target-version = "py310"
# We only support Python 3.10+, this is the minimum version.
# This will need to be updated when we start to support Python 3.10+ specific syntax.

lint.select = [
    "E4",
    "E7",
    "E9", # pycodestyle errors
    "F",  # Pyflakes
]
lint.ignore = ["F401", "E203", "W291", "F841"]

[tool.ruff.lint.per-file-ignores]
# "**/{tests,docs,tools}/*" = ["E402"]
"__init__.py" = ["E402", "F401"]
# module level import of this package need before boorust setup
"qurry/process/utils/dummy.py" = ["E731"]
# The only file allows lambda assignment for a specific function

# Respecting command line options of ruff
# This will be useful when you configure ruff in your IDE
# ruff check 
# --line-length=100 --target-version=py310 --select=E4,E7,E9,F 
# --ignore=F401,E203,W291,F841 ./qurry
# Or with format:
# ruff format --line-length=100 ./qurry
