name: Test Unit
author: Harui (Huai-Chun Chang)
description: The basic unit to test Qurrium.
branding:
  icon: "check"
  color: "blue"
inputs:
  python-version:
    description: The Python version to test
    required: true
    default: "3.13"
  qiskit-version:
    description: The Qiskit version to test
    required: false
    default: "v2"

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Check OS
      run: |
        echo "======================================================================"
        echo "### Test ............................................................."
        echo "======================================================================"
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "| This action is not yet proved to work on Windows"
        else
          echo "| This action is proved to work on UNIX-like $RUNNER_OS"
        fi
      shell: bash

    - name: Install Rust toolchain
      shell: bash
      run: |
        rustup self update
        echo "| Installing rustup"
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
        source "$HOME/.cargo/env"
        echo "| Installing Rust toolchain from rust-toolchain.toml"
        rustup show

        rustup component add cargo --toolchain 1.85
        rustup default 1.85  # Just to be sure
        # --------------------------------------------------------------------------
        # Playing: BIRDBRAIN (w/ OK Glass) feat. Kasane Teto
        # So, Fxxk (To fix this.)

    - name: Install Tools
      shell: bash
      run: |
        python -m pip install --upgrade pipenv wheel pip auditwheel auditwheel-symbols delocate setuptools_rust setuptools pkginfo toml pep440

    - name: Install Qiskit and Qurrium
      shell: bash
      run: |
        if [[ "${{ inputs.qiskit-version }}" == "v0" ]]; then
          echo "| Installing Qiskit v0 (Oldest supported version 0.45)"
          python -m pip install ".[dev,qiskit-aer]" "qiskit>=0.45.0,<1.0.0" --no-cache-dir
        elif [[ "${{ inputs.qiskit-version }}" == "v1" ]]; then
          echo "| Installing Qiskit v1"
          python -m pip install ".[dev,qiskit-aer]" "qiskit>=1.0.0,<2.0.0" --no-cache-dir
        elif [[ "${{ inputs.qiskit-version }}" == "v2" ]]; then
          echo "| Installing Qiskit v2"
          python -m pip install ".[dev,qiskit-aer]" "qiskit>=2.0.0" --no-cache-dir
        else
          echo "| Invalid Qiskit version specified: ${{ inputs.qiskit-version }}"
          echo "| Please specify 'v0', 'v1', or 'v2' for the Qiskit version input."
          exit 1
        fi

    - name: Test with pytest
      shell: bash
      run: |
        python -m pytest -v -s --durations=0
