# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - pre-release
      - pre-release-*
      - main
      - main-*
      - dev
      - dev-*

jobs:
  check_version:
    name: Check Version and Lint Check
    runs-on: [ubuntu-latest, self-hosted]
    outputs:
      skip: ${{ steps.skip_test.outputs.skip }}
      idle: ${{ steps.detect.outputs.idle }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Fetch all tags
        run: |
          git fetch --prune --tags --force

      - name: Check Version
        id: check_version
        run: |
          python -m pip install pep440
          python ./tools/set_version.py

      - name: Check out Version
        run: |
          echo "| Version: ${{ steps.check_version.outputs.VERSION }} in action"
          echo "| Tag exists: ${{ steps.check_version.outputs.exists }}"

      - name: Whether Skip Test
        run: |
          if [[ "${{ github.event.pull_request.title }}" == skip-test:* ]]; then
            echo "| Skip Test"
          fi

      - name: Lint with flake8
        run: |
          python -m pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --count --show-source --statistics --config tox.ini
          # exit-zero treats all errors as warnings
          python -m flake8 . --count --exit-zero --statistics --config tox.ini

      - name: Whether to skip test
        id: skip_test
        run: |
          if [[ ${{ contains(github.event.pull_request.title, 'skip-version:') }} ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Decide Idle Github Action Self-Hosted Runner Number
        id: detect
        run: |
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}

          # Call GitHub API to get runners
          RESP=$(curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${OWNER}/${REPO}/actions/runners)

          # Parse number of idle runners (online + not busy)
          IDLE=$(echo "$RESP" | jq '[.runners[] | select(.status == "online")] | length')

          echo "Detected idle runners: $IDLE"
          echo "idle=$IDLE" >> "$GITHUB_OUTPUT"

  test_py:
    name: Test
    runs-on: [ubuntu-latest, self-hosted]
    needs:
      - check_version
    if: needs.check_version.outputs.skip != 'true'
    strategy:
      matrix:
        qiskit-version: [v1, v2]
        python-version: ["3.13", "3.9", "3.12", "3.11", "3.10"]
      fail-fast: false
      max-parallel: ${{ needs.check_version.outputs.idle || 2 }}

    steps:
      - uses: actions/checkout@v4
      - name: Run Test Unit with Python ${{ matrix.python-version }} and Qiskit ${{ matrix.qiskit-version }}

        uses: ./.github/actions/test-unit
        with:
          python-version: ${{ matrix.python-version }}
          qiskit-version: ${{ matrix.qiskit-version }}
