# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - pre-release
      - pre-release-*
      - main
      - main-*
      - dev
      - dev-*

jobs:
  check_version:
    name: Check Version and Lint Check
    runs-on: [ubuntu-latest, self-hosted]
    outputs:
      idle: ${{ steps.detect.outputs.idle }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Fetch all tags
        run: |
          git fetch --prune --tags --force

      - name: Check Version
        id: check_version
        run: |
          python -m pip install pep440
          python ./tools/set_version.py

      - name: Check out Version
        run: |
          echo "| Version: ${{ steps.check_version.outputs.VERSION }} in action"
          echo "| Tag exists: ${{ steps.check_version.outputs.exists }}"

      - name: Install Qurrium
        run: |
          python -m pip install ".[dev,qiskit-aer]"

      - name: Lint with Pylint
        run: |
          python -m pip install pylint
          pylint --rcfile pyproject.toml ./qurry
          # stop the process if pylint finds any issues
          if [ $? -ne 0 ]; then
            echo "| Pylint found issues. Please fix them before proceeding."
            exit 1
          fi

      - name: Lint with Ruff
        run: |
          python -m pip install ruff
          ruff check --config pyproject.toml
          # stop the process if ruff finds any issues
          if [ $? -ne 0 ]; then
            echo "| Ruff found issues. Please fix them before proceeding."
            exit 1
          fi

      - name: Decide Idle Github Action Self-Hosted Runner Number
        id: detect
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_MANAGER_TOKEN }}
          # Require the tokens owned Organization access to review the self-hosted runners.
          # If the token is owned by a user, it will not be able to access the self-hosted runners.
        run: |
          ORGS=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}

          # Call GitHub API to get runners
          RESP_ORGS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/orgs/${ORGS}/actions/runners)
          RESP_REPO=$(curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${ORGS}/${REPO}/actions/runners)

          RESP_ORGS_SUCCESS=$(echo "$RESP_ORGS" | jq -r '.message // empty')
          RESP_REPO_SUCCESS=$(echo "$RESP_REPO" | jq -r '.message // empty')

          if [ -n "$RESP_ORGS_SUCCESS" ] || [ -n "$RESP_REPO_SUCCESS" ]; then
              echo "| Error fetching repository runners: $RESP_REPO"
              echo "| Error fetching organization runners: $RESP_ORGS"
              IDLE_ORGS=0
              IDLE_REPO=0
          else
              echo "| Successfully fetched runners for organization and repository."
              # Parse number of idle runners (online)
              IDLE_ORGS=$(echo "$RESP_ORGS" | jq '[.runners[] | select(.status == "online" and .busy == false)] | length' || echo 0)
              IDLE_REPO=$(echo "$RESP_REPO" | jq '[.runners[] | select(.status == "online" and .busy == false)] | length' || echo 0)
          fi

          echo "| Detected idle runners in org: $IDLE_ORGS"
          echo "| Detected idle runners in repo: $IDLE_REPO"
          TOTAL_IDLE=$((IDLE_ORGS + IDLE_REPO))
          echo "| Detected idle runners total: $TOTAL_IDLE"
          DECIDE=$((TOTAL_IDLE > 0 ? TOTAL_IDLE : 4))
          echo "| Decision: $DECIDE"

          echo "idle=$DECIDE" >> "$GITHUB_OUTPUT"

  test_py:
    name: Test
    runs-on: [ubuntu-latest, self-hosted]
    needs:
      - check_version
    if: ${{ !contains(github.event.pull_request.title, 'skip-test:') }}
    strategy:
      matrix:
        qiskit-version: [v1, v2]
        python-version: ["3.14", "3.13", "3.12", "3.11", "3.10"]
      fail-fast: false
      max-parallel: ${{ fromJSON(needs.check_version.outputs.idle || '4') }}

    steps:
      - uses: actions/checkout@v4
      - name: Run Test Unit with Python ${{ matrix.python-version }} and Qiskit ${{ matrix.qiskit-version }}

        uses: ./.github/actions/test-unit
        with:
          python-version: ${{ matrix.python-version }}
          qiskit-version: ${{ matrix.qiskit-version }}
