# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request:
    branches:
      - pre-release
      - pre-release-*
      - main
      - main-*
      - dev
      - dev-*

jobs:
  check_version:
    name: Check Version
    runs-on: [ubuntu-latest, self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Fetch all tags
        run: |
          git fetch --prune --tags --force

      - name: Check Version
        id: check_version
        run: |
          python -m pip install pep440
          python ./tools/set_version.py

      - name: Check out Version
        run: |
          echo "| Version: ${{ steps.check_version.outputs.VERSION }} in action"
          echo "| Tag exists: ${{ steps.check_version.outputs.exists }}"

      - name: Whether Skip Test
        run: |
          if [[ "${{ github.event.pull_request.title }}" == skip-test:* ]]; then
            echo "| Skip Test"
          fi

  test_py_latest_and_oldest:
    if: ${{ !startsWith(github.event.pull_request.title, 'skip-test:') }}
    name: Test on Python Latest and Oldest
    runs-on: [ubuntu-latest, self-hosted]
    needs:
      - check_version
    strategy:
      matrix:
        include:
          - step: python-latest
            depends_on: []
            python-version: "3.13"
            qiskit-v1: "no"
          - step: python-oldest
            depends_on: [python-latest]
            python-version: "3.9"
            qiskit-v1: "no"
          - step: python-latest-qiskit-v1
            depends_on: [python-oldest]
            python-version: "3.13"
            qiskit-v1: "yes"
          - step: python-oldest-qiskit-v1
            depends_on: [python-latest-qiskit-v1]
            python-version: "3.9"
            qiskit-v1: "yes"
      fail-fast: false
      max-parallel: 3

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Is Qiskit v1
        run: |
          if [[ "${{ matrix.qiskit-v1 }}" == "yes" ]]; then
            echo "Qiskit v1"
          else
            echo "Qiskit v2"
          fi

      - name: Run Test Unit
        uses: ./.github/actions/test-unit
        with:
          qiskit-v1: ${{ matrix.qiskit-v1 }}

  test_py:
    if: ${{ !startsWith(github.event.pull_request.title, 'skip-test:') }}
    name: Test on Python
    runs-on: [ubuntu-latest, self-hosted]
    needs:
      - check_version
      - test_py_latest_and_oldest
    strategy:
      matrix:
        include:
          - step: py-other-310
            depends_on: []
            python-version: "3.10"
            qiskit-v1: "no"
          - step: py-other-311
            depends_on: [py-other-310]
            python-version: "3.11"
            qiskit-v1: "no"
          - step: py-other-312
            depends_on: [py-other-311]
            python-version: "3.12"
            qiskit-v1: "no"
          - step: py-other-310-qiskit-v1
            depends_on: [py-other-312]
            python-version: "3.10"
            qiskit-v1: "yes"
          - step: py-other-311-qiskit-v1
            depends_on: [py-other-310-qiskit-v1]
            python-version: "3.11"
            qiskit-v1: "yes"
          - step: py-other-312-qiskit-v1
            depends_on: [py-other-311-qiskit-v1]
            python-version: "3.12"
            qiskit-v1: "yes"
      fail-fast: false
      max-parallel: 3

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Is Qiskit v1
        run: |
          if [[ "${{ matrix.qiskit-v1 }}" == "yes" ]]; then
            echo "Qiskit v1"
          else
            echo "Qiskit v2"
          fi

      - name: Run Test Unit
        uses: ./.github/actions/test-unit
        with:
          qiskit-v1: ${{ matrix.qiskit-v1 }}
