name: Upload Wheel to PyPI
on:
  workflow_dispatch:
    inputs:
      wheel_path:
        description: "Wheel Path"
        required: true
        type: string
      wheel_name:
        description: "Wheel Name"
        required: true
        type: string
      repository_url:
        description: "PyPI URL"
        required: false
        default: "https://test.pypi.org/legacy/"
        type: string

jobs:
  upload_wheel:
    name: Upload Wheel to PyPI
    runs-on: wheel-keeper
    permissions:
      id-token: write # 用於 PyPI 的可信發布

    environment:
      name: testpypi # 或 pypi
      url: https://test.pypi.org/p/qurry

    steps:
      - name: Copy wheel from local path
        run: |
          mkdir -p dist
          cp "${{ inputs.wheel_path }}/${{ inputs.wheel_name }}" dist/
          ls -la dist/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: ${{ inputs.repository_url || 'https://test.pypi.org/legacy/' }}
          skip-existing: true
