name: Upload Wheel to PyPI
on:
  repository_dispatch:
    types: [upload_wheel]

jobs:
  upload_wheel:
    name: Upload Wheel to PyPI
    runs-on: wheel-keeper
    permissions:
      id-token: write # 用於 PyPI 的可信發布

    environment:
      name: testpypi # 或 pypi
      url: https://test.pypi.org/p/qurry

    steps:
      - name: Copy wheel from local path
        run: |
          mkdir -p dist
          cp "${{ github.event.client_payload.wheel_path }}/${{ github.event.client_payload.wheel_name }}" dist/
          ls -la dist/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: ${{ github.event.client_payload.repository_url || 'https://upload.pypi.org/legacy/' }}
          skip-existing: true
