---
name: Wheel Builds Stable
on:
  push:
    tags:
      - 0.[0-9]+.[0-9]+
      - 0.[0-9]+.[0-9]+.dev[0-9]+

jobs:
  build_wheels:
    if: github.repository == 'qurrium/qurry'
    name: Build wheels on ${{ matrix.system-arch }} by ${{ matrix.os }}
    runs-on: ${{ matrix.full-os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - system-arch: linux-x86_64
            os: ubuntu-latest
            archs: X64
            full-os: [ubuntu-latest, self-hosted]
          # - system-arch: linux-aarch64
          #   os: ubuntu-24.04-arm
          #   archs: ARM64
          #   full-os: [ubuntu-24.04-arm]
          # - system-arch: macOS-x86_64
          #   os: macos-13
          #   archs: X64
          #   full-os: [macos-13]
          # - system-arch: macOS-arm64
          #   os: macos-14
          #   archs: ARM64
          #   full-os: [macos-14]
          # - system-arch: windows-x86_64
          #   os: windows-latest
          #   archs: X64
          #   full-os: [windows-latest]

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    outputs:
      call-publish: ${{ steps.build_wheels.outputs.call-publish }}

    environment:
      name: pypi
      url: https://pypi.org/p/qurrium

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wheel Build
        uses: ./.github/actions/wheel-build
        id: build_wheels
        with:
          system-arch: ${{ matrix.system-arch }}
          os: ${{ matrix.os }}
          release: stable
          python-version: 3.12

      - name: Whether need to upload wheelhouse from upload-artifact
        id: upload_check
        run: |
          if [[ "${{ matrix.system-arch }}" == "linux-x86_64" ]]; then
            echo "upload=false" >> $GITHUB_OUTPUT
          else
            echo "upload=true" >> $GITHUB_OUTPUT
          fi

      # Upload the wheelhouse as an artifact
      - name: Wheelhouse Upload
        if: matrix.system-arch != 'linux-x86_64'
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: shared-wheel-builds

      - name: Early Publish distribution 📦 to PyPI for Linux X86_64
        if: matrix.system-arch == 'linux-x86_64'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse

      # - name: Early Publish distribution 📦 to TestPyPI for Linux X86_64
      #   if: matrix.system-arch == 'linux-x86_64'
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     packages-dir: wheelhouse
      #     repository-url: https://test.pypi.org/legacy/

  # publish-to-pypi:
  #   if: github.repository == 'qurrium/qurry'
  #   name: Publish Python 🐍 distribution 📦 to PyPI
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build_wheels
  #   permissions:
  #     id-token: write # IMPORTANT: mandatory for trusted publishing

  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/qurrium

  #   steps:
  #     - name: Download all the dists
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: shared-wheel-builds
  #         path: deploy

  #     - name: Publish distribution 📦 to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         packages-dir: deploy
