---
name: Wheel Builds Nightly
on:
  push:
    tags:
      - 0.[0-9]+.[0-9]+.dev[0-9]+

jobs:
  build_wheels:
    if: github.repository == 'qurrium/qurry'
    name: Build wheels on ${{ matrix.vers }} by ${{ matrix.os }}
    runs-on:
      - ${{ matrix.os }}
      - self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - vers: linux-x86_64
            os: ubuntu-latest
            archs: X64
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    environment:
      name: testpypi
      url: https://test.pypi.org/p/qurry

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: ${{ matrix.os == 'macos-14' && 'arm64' || 'x64' }}
      - name: MacOS Path Fix
        if: runner.os == 'macOS'
        run: export PATH="$pythonLocation:$PATH"

      - name: Reversion Nightly
        run: |
          python -m pip install toml pep440
          python ./tools/set_version.py --release nightly
          python ./tools/set_pyproject_qurry.py --release nightly

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Set up
      # - name: Set up QEMU
      #   if: matrix.vers == 'linux-aarch64'
      #   uses: docker/setup-qemu-action@v3
      #   with:
      #     platforms: all

      - name: Prepare CIBW
        run: |
          python -m pip install cibuildwheel --upgrade
          echo "| $(python -m pip --version)"
          echo "| $(python -m pip list | grep cibuildwheel)"

      # Build wheels
      - name: Build wheels
        if: matrix.vers != 'linux-aarch64'
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - name: Build wheels (Linux aarch64)
        if: matrix.vers == 'linux-aarch64'
        run: |
          python -m cibuildwheel --output-dir wheelhouse --platform linux --arch aarch64

      # Upload the wheelhouse as an artifact
      # - name: Wheelhouse Upload
      #   if: matrix.vers != 'linux-x86_64'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: ./wheelhouse/*.whl
      #     name: shared-wheel-builds

      - name: Early Publish distribution 📦 to TestPyPI for Linux X86_64
        if: matrix.vers == 'linux-x86_64'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse
          repository-url: https://test.pypi.org/legacy/

      - name: Clean up Docker Image of PyPI Publish
        if: matrix.vers == 'linux-x86_64'
        run: |
          # Remove the Docker image of ghcr.io/pypa/gh-action-pypi-publish:release-v1
          # Prevent using outdated image
          docker rmi -f $(docker images -q ghcr.io/pypa/gh-action-pypi-publish:release-v1) || echo "No image found"
