---
name: Wheel Builds Stable
on:
  push:
    tags:
      - 0.[0-9]+.[0-9]+

jobs:
  build_wheels:
    if: github.repository == 'qurrium/qurry'
    name: Build wheels on ${{ matrix.system-arch }} by ${{ matrix.os }}${{ matrix.self-hosted && ' (self-hosted)' || '' }}
    runs-on: ${{ matrix.self-hosted == true && format('[{0}, self-hosted]', matrix.os) || matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - system-arch: linux-x86_64
            os: ubuntu-latest
            archs: X64
            self-hosted: true
          # - system-arch: linux-aarch64
          #   os: ubuntu-24.04-arm
          #   archs: ARM64
          # - system-arch: macOS-x86_64
          #   os: macos-13
          #   archs: X64
          # - system-arch: macOS-arm64
          #   os: macos-14
          #   archs: ARM64
          # - system-arch: windows-x86_64
          #   os: windows-latest
          #   archs: X64

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    outputs:
      call-publish: ${{ steps.build_wheels.outputs.call-publish }}

    environment:
      name: pypi
      url: https://pypi.org/p/qurrium

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wheel Build
        uses: ./.github/actions/wheel-build
        id: build_wheels
        with:
          system-arch: ${{ matrix.system-arch }}
          os: ${{ matrix.os }}
          release: nightly

      - name: Clean up Docker Image of PyPI Publish
        if: runner.environment == 'self-hosted'
        run: |
          # Remove the Docker image of ghcr.io/pypa/gh-action-pypi-publish:release-v1
          # Prevent using outdated image
          docker rmi -f $(docker images -q ghcr.io/pypa/gh-action-pypi-publish:release-v1) || echo "No image found"

  publish-to-pypi:
    if: github.repository == 'qurrium/qurry' && needs.build_wheels.outputs.call-publish == 'true'
    name: Publish Python 🐍 distribution 📦 to PyPI
    runs-on: ubuntu-latest
    needs:
      - build_wheels
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/qurrium

    steps:
      - uses: ./.github/actions/wheel-publish
        id: publish_wheels
        with:
          release: stable
